<script lang="ts">
	interface DomainItem {
		domain: string;
		count: number;
		percentage: number;
	}

	interface Props {
		domains?: DomainItem[];
		totalCourses?: number;
		title?: string;
	}

	let {
		domains = [
			{ domain: 'Computer Science & AI', count: 6, percentage: 55 },
			{ domain: 'Mathematics & Logic', count: 2, percentage: 18 },
			{ domain: 'Physical & Natural Sciences', count: 1, percentage: 9 },
			{ domain: 'Humanities & Social Sciences', count: 1, percentage: 9 },
			{ domain: 'Business & Economics', count: 1, percentage: 9 }
		],
		totalCourses = 11,
		title = 'Curriculum & Subject Domain Breakdown'
	}: Props = $props();

	const domainColorMap: Record<string, { bg: string; text: string; dot: string; icon: string }> = {
		'Computer Science & AI': { bg: 'bg-primary/10', text: 'text-primary', dot: 'bg-primary', icon: '💻' },
		'Mathematics & Logic': { bg: 'bg-emerald-500/10', text: 'text-emerald-500', dot: 'bg-emerald-500', icon: '📐' },
		'Physical & Natural Sciences': { bg: 'bg-amber-500/10', text: 'text-amber-500', dot: 'bg-amber-500', icon: '🔬' },
		'Humanities & Social Sciences': { bg: 'bg-indigo-500/10', text: 'text-indigo-500', dot: 'bg-indigo-500', icon: '🏛️' },
		'Business & Economics': { bg: 'bg-rose-500/10', text: 'text-rose-500', dot: 'bg-rose-500', icon: '📈' },
		'Languages & General': { bg: 'bg-teal-500/10', text: 'text-teal-500', dot: 'bg-teal-500', icon: '🌍' }
	};
</script>

<div class="flex flex-col justify-between rounded-2xl border border-border bg-surface p-5 shadow-xs">
	<!-- Header -->
	<div class="flex items-center justify-between">
		<div>
			<div class="flex items-center gap-2">
				<h3 class="font-display text-sm font-bold text-text">{title}</h3>
				<span class="rounded-md bg-violet-500/10 px-2 py-0.5 text-[10px] font-bold text-violet-500">
					Taxonomy
				</span>
			</div>
			<p class="mt-0.5 text-xs text-text-muted">
				Academic disciplines of courses generated by students and instructors.
			</p>
		</div>
		<span class="text-xs font-semibold text-text-muted">{totalCourses} Courses</span>
	</div>

	<!-- Stacked Multi-Color Segment Bar -->
	<div class="my-4 flex flex-col gap-2">
		<div class="flex h-3 w-full overflow-hidden rounded-full bg-surface-muted">
			{#each domains as d (d.domain)}
				{@const colors = domainColorMap[d.domain] || { dot: 'bg-primary' }}
				<div
					class="h-full {colors.dot} transition-all duration-500"
					style="width: {d.percentage}%;"
					title="{d.domain}: {d.count} ({d.percentage}%)"
				></div>
			{/each}
		</div>
	</div>

	<!-- Grid of Domain Cards -->
	<div class="grid grid-cols-1 gap-2.5 sm:grid-cols-2">
		{#each domains as d (d.domain)}
			{@const colors = domainColorMap[d.domain] || { bg: 'bg-surface-muted', text: 'text-text', dot: 'bg-primary', icon: '📚' }}
			<div class="flex items-center justify-between rounded-xl border border-border/60 bg-surface-muted/50 p-2.5 transition-colors hover:bg-surface-muted">
				<div class="flex items-center gap-2 min-w-0">
					<span class="text-base">{colors.icon}</span>
					<div class="min-w-0">
						<span class="block truncate text-xs font-bold text-text">{d.domain}</span>
						<span class="block text-[10px] text-text-muted">{d.count} course{d.count === 1 ? '' : 's'}</span>
					</div>
				</div>
				<span class="font-mono text-xs font-bold {colors.text}">{d.percentage}%</span>
			</div>
		{/each}
	</div>

	<!-- Footer -->
	<div class="mt-3 flex items-center justify-between border-t border-border/50 pt-2 text-[11px] text-text-muted">
		<span>Auto-classified via course outline concepts.</span>
		<span class="font-medium text-primary">Live Distribution</span>
	</div>
</div>
